/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import java.io.IOException;

/**
 * Clase MenuPrincipal:
 * Interfaz grafica encargada de dar las multiples opciones al usuario.
 */
public class MenuPrincipal extends javax.swing.JFrame {
    /**
     * Atributos:
     * Las distintas ventanas a ocupar.
     */
    private ManejoDeColecciones manejo;
    private VentanaMostrarConsultas mostrarConsultas;
    private VentanaAgregarConsulta anadirConsulta;
    private VentanaMostrarTemas mostrarTemas;
    private VentanaEditarConsulta editarConsulta;
    private VentanaEliminarConsulta eliminarConsulta;
    private VentanaMostrarConFiltro mostrarFiltro;
    private VentanaMostrarMasVotos mostrarIdFiltro;
    private VentanaMostrarGrafico mostrarGrafico;
    private VentanaAgregarRespuestaBinaria anadirRespuesta;
    private VentanaEliminarTema eliminarTema;
    private VentanaEditarTema editarTema;
    private VentanaAgregarTema agregarTema;
    private VentanaAgregarRespuestaMultiple agregarRespuestaM;
    private VentanaErrorField ventanaAviso;
    private ReportableStrategy reporteEstrategia;
    
    
    public MenuPrincipal(ManejoDeColecciones manejo) {
        initComponents();
        this.manejo = new ManejoDeColecciones();
        this.manejo= manejo;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonVerConsultas = new javax.swing.JButton();
        botonAgregarConsultas = new javax.swing.JButton();
        botonVerTemas = new javax.swing.JButton();
        botonAgregarRespuestaBinaria = new javax.swing.JButton();
        botonEditarConsulta = new javax.swing.JButton();
        botonEliminarConsulta = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonVerConsultaPorTema = new javax.swing.JButton();
        botonConsultaTemaEID = new javax.swing.JButton();
        botonMostrarGrafico = new javax.swing.JButton();
        botonEliminarTema = new javax.swing.JButton();
        botonEditarTema = new javax.swing.JButton();
        botonAgregarTema = new javax.swing.JButton();
        botonRespuestaMultiple = new javax.swing.JButton();
        reporteConsultaBinariaTxt = new javax.swing.JButton();
        reporteConsultaBinariaExcel = new javax.swing.JButton();
        reporteConsultaMultipleTxt = new javax.swing.JButton();
        reporteConsultaMultipleXlsx = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenidos al sistema de Consulta Ciudadanas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Eliga una opcion");

        botonVerConsultas.setText("Ver Consultas");
        botonVerConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerConsultasActionPerformed(evt);
            }
        });

        botonAgregarConsultas.setText("Agregar Consulta");
        botonAgregarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarConsultasActionPerformed(evt);
            }
        });

        botonVerTemas.setText("Ver Temas");
        botonVerTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerTemasActionPerformed(evt);
            }
        });

        botonAgregarRespuestaBinaria.setText("Agregar Respuesta Simple");
        botonAgregarRespuestaBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarRespuestaBinariaActionPerformed(evt);
            }
        });

        botonEditarConsulta.setText("Editar Consultas");
        botonEditarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarConsultaActionPerformed(evt);
            }
        });

        botonEliminarConsulta.setText("Eliminar Consulta");
        botonEliminarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarConsultaActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonVerConsultaPorTema.setText("Ver Consulta por tema");
        botonVerConsultaPorTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerConsultaPorTemaActionPerformed(evt);
            }
        });

        botonConsultaTemaEID.setText("Ver Consulta Con Mas Votos");
        botonConsultaTemaEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaTemaEIDActionPerformed(evt);
            }
        });

        botonMostrarGrafico.setText("Mostrar Grafico");
        botonMostrarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarGraficoActionPerformed(evt);
            }
        });

        botonEliminarTema.setText("Eliminar Tema");
        botonEliminarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTemaActionPerformed(evt);
            }
        });

        botonEditarTema.setText("Editar Tema");
        botonEditarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarTemaActionPerformed(evt);
            }
        });

        botonAgregarTema.setText("Agregar tema");
        botonAgregarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarTemaActionPerformed(evt);
            }
        });

        botonRespuestaMultiple.setText("Agregar Respuesta Multiple");
        botonRespuestaMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRespuestaMultipleActionPerformed(evt);
            }
        });

        reporteConsultaBinariaTxt.setText("Reporte Consultas Binarias (txt)");
        reporteConsultaBinariaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteConsultaBinariaTxtActionPerformed(evt);
            }
        });

        reporteConsultaBinariaExcel.setText("Reporte Consultas Binarias (xlsx)");
        reporteConsultaBinariaExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteConsultaBinariaExcelActionPerformed(evt);
            }
        });

        reporteConsultaMultipleTxt.setText("Reporte Consulta Multiple (txt)");
        reporteConsultaMultipleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteConsultaMultipleTxtActionPerformed(evt);
            }
        });

        reporteConsultaMultipleXlsx.setText("Reporte Consulta Multiple (xlsx)");
        reporteConsultaMultipleXlsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteConsultaMultipleXlsxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reporteConsultaMultipleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reporteConsultaBinariaExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reporteConsultaBinariaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMostrarGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditarTema, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarTema, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRespuestaMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarRespuestaBinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(reporteConsultaMultipleXlsx, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAgregarTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVerConsultaPorTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonConsultaTemaEID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVerTemas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVerConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVerConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVerTemas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonConsultaTemaEID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVerConsultaPorTema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregarTema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregarRespuestaBinaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRespuestaMultiple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregarConsultas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminarConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminarTema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEditarTema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEditarConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonMostrarGrafico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reporteConsultaBinariaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reporteConsultaBinariaExcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reporteConsultaMultipleTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reporteConsultaMultipleXlsx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerConsultasActionPerformed
       this.setVisible(false);
       this.mostrarConsultas = new VentanaMostrarConsultas(this, manejo);
       mostrarConsultas.setVisible(true);
    }//GEN-LAST:event_botonVerConsultasActionPerformed

    private void botonAgregarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarConsultasActionPerformed
        this.setVisible(false);
        this.anadirConsulta= new VentanaAgregarConsulta(manejo,this);
        this.anadirConsulta.setVisible(true);
    }//GEN-LAST:event_botonAgregarConsultasActionPerformed

    private void botonVerTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerTemasActionPerformed
        this.setVisible(false);
        this.mostrarTemas = new VentanaMostrarTemas (this,manejo);
        this.mostrarTemas.setVisible(true);
        mostrarTemas.mostrarTemas();
    }//GEN-LAST:event_botonVerTemasActionPerformed

    private void botonAgregarRespuestaBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarRespuestaBinariaActionPerformed
        this.setVisible(false);
        this.anadirRespuesta = new VentanaAgregarRespuestaBinaria(manejo,this);
        this.anadirRespuesta.setVisible(true);
        anadirRespuesta.mostrarTemas();
    }//GEN-LAST:event_botonAgregarRespuestaBinariaActionPerformed

    private void botonEditarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarConsultaActionPerformed
        editarConsulta = new VentanaEditarConsulta(manejo,this);
        editarConsulta.setVisible(true);
        editarConsulta.mostrarTemas();
    }//GEN-LAST:event_botonEditarConsultaActionPerformed

    private void botonEliminarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarConsultaActionPerformed
        eliminarConsulta = new VentanaEliminarConsulta(manejo,this);
        eliminarConsulta.setVisible(true);
        eliminarConsulta.mostrarTemas();
    }//GEN-LAST:event_botonEliminarConsultaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
        System.exit(0);
        
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonVerConsultaPorTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerConsultaPorTemaActionPerformed
        this.setVisible(false);
        this.mostrarFiltro= new VentanaMostrarConFiltro(this,manejo);
        this.mostrarFiltro.setVisible(true);
        this.mostrarFiltro.mostrarTemas();
    }//GEN-LAST:event_botonVerConsultaPorTemaActionPerformed

    private void botonConsultaTemaEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaTemaEIDActionPerformed
        this.setVisible(false);
        this.mostrarIdFiltro= new VentanaMostrarMasVotos(this, manejo);
        mostrarIdFiltro.setVisible(true);
        mostrarIdFiltro.mostrarTemas();
    }//GEN-LAST:event_botonConsultaTemaEIDActionPerformed

    private void botonMostrarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarGraficoActionPerformed
        this.setVisible(false);
        this.mostrarGrafico = new VentanaMostrarGrafico (this, manejo);
        this.mostrarGrafico.setVisible(true);
    }//GEN-LAST:event_botonMostrarGraficoActionPerformed

    private void botonEliminarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTemaActionPerformed
        this.setVisible(false);
        this.eliminarTema = new VentanaEliminarTema(this.manejo , this);
        this.eliminarTema.setVisible(true);
        this.eliminarTema.mostrarTemas();
    }//GEN-LAST:event_botonEliminarTemaActionPerformed

    private void botonEditarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarTemaActionPerformed
        this.editarTema = new VentanaEditarTema(this.manejo , this);
        this.editarTema.setVisible(true);
        this.editarTema.mostrarTemas();
    }//GEN-LAST:event_botonEditarTemaActionPerformed

    private void botonAgregarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarTemaActionPerformed
        this.agregarTema = new VentanaAgregarTema(this.manejo , this);
        this.agregarTema.setVisible(true);
    }//GEN-LAST:event_botonAgregarTemaActionPerformed

    private void botonRespuestaMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRespuestaMultipleActionPerformed
        this.setVisible(false);
        this.agregarRespuestaM = new VentanaAgregarRespuestaMultiple(manejo,this);
        this.agregarRespuestaM.setVisible(true);
        this.agregarRespuestaM.mostrarTemas();
        this.agregarRespuestaM.mostrarVotos();
    }//GEN-LAST:event_botonRespuestaMultipleActionPerformed

    private void reporteConsultaBinariaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteConsultaBinariaTxtActionPerformed
        // TODO add your handling code here:
        try{
            this.reporteEstrategia = new ReporteConsultaBinaria(manejo.matrizConsultasSimples("Reporte"));
            this.reporteEstrategia.generarTxt();
            this.ventanaAviso = new VentanaErrorField("Archivo txt generado con exito");
            this.ventanaAviso.setVisible(true);
        }
        catch(IOException e){
            this.ventanaAviso = new VentanaErrorField("NO SE A PODIDO GENERAR EL ARCHIVO");
            this.ventanaAviso.setVisible(true);
        }
    }//GEN-LAST:event_reporteConsultaBinariaTxtActionPerformed

    private void reporteConsultaBinariaExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteConsultaBinariaExcelActionPerformed
        try{
            this.reporteEstrategia = new ReporteConsultaBinaria(manejo.matrizConsultasSimples("Reporte"));
            this.reporteEstrategia.generarExcel();
            this.ventanaAviso = new VentanaErrorField("Archivo xlsx generado con exito");
            this.ventanaAviso.setVisible(true);
        }
        catch(IOException e){
            this.ventanaAviso = new VentanaErrorField("NO SE A PODIDO GENERAR EL ARCHIVO");
            this.ventanaAviso.setVisible(true);
        }
    }//GEN-LAST:event_reporteConsultaBinariaExcelActionPerformed

    private void reporteConsultaMultipleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteConsultaMultipleTxtActionPerformed
        try{
            this.reporteEstrategia = new ReporteConsultaMultiple(manejo.matrizConsultasMultiple("reporte"));
            this.reporteEstrategia.generarTxt();
            this.ventanaAviso = new VentanaErrorField("Archivo txt generado con exito");
            this.ventanaAviso.setVisible(true);
        }
        catch(IOException e){
            this.ventanaAviso = new VentanaErrorField("NO SE A PODIDO GENERAR EL ARCHIVO");
            this.ventanaAviso.setVisible(true);
        }
    }//GEN-LAST:event_reporteConsultaMultipleTxtActionPerformed

    private void reporteConsultaMultipleXlsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteConsultaMultipleXlsxActionPerformed
        try{
            this.reporteEstrategia = new ReporteConsultaMultiple(manejo.matrizConsultasMultiple("reporte"));
            this.reporteEstrategia.generarExcel();
            this.ventanaAviso = new VentanaErrorField("Archivo xlsx generado con exito");
            this.ventanaAviso.setVisible(true);
        }
        catch(IOException e){
            this.ventanaAviso = new VentanaErrorField("NO SE A PODIDO GENERAR EL ARCHIVO");
            this.ventanaAviso.setVisible(true);
        }
    }//GEN-LAST:event_reporteConsultaMultipleXlsxActionPerformed

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarConsultas;
    private javax.swing.JButton botonAgregarRespuestaBinaria;
    private javax.swing.JButton botonAgregarTema;
    private javax.swing.JButton botonConsultaTemaEID;
    private javax.swing.JButton botonEditarConsulta;
    private javax.swing.JButton botonEditarTema;
    private javax.swing.JButton botonEliminarConsulta;
    private javax.swing.JButton botonEliminarTema;
    private javax.swing.JButton botonMostrarGrafico;
    private javax.swing.JButton botonRespuestaMultiple;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVerConsultaPorTema;
    private javax.swing.JButton botonVerConsultas;
    private javax.swing.JButton botonVerTemas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton reporteConsultaBinariaExcel;
    private javax.swing.JButton reporteConsultaBinariaTxt;
    private javax.swing.JButton reporteConsultaMultipleTxt;
    private javax.swing.JButton reporteConsultaMultipleXlsx;
    // End of variables declaration//GEN-END:variables
}
