/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;

/**
 *
 * @author sebas
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private ManejoDeColecciones manejo;
    private VentanaConsultas mostrarConsultas;
    private VentanaAnadir anadirConsulta;
    private VentanaMostrarTemas mostrarTemas;
    private VentanaEditarPregunta editarConsulta;
    private VentanaEliminarConsulta eliminarConsulta;
    private VentanaMostrarConFiltro mostrarFiltro;
    private VentanaMostrarIdYTema mostrarIdFiltro;
    private VentanaMostrarGrafico mostrarGrafico;
    private VentanaAgregarRespuesta anadirRespuesta;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(ManejoDeColecciones manejo) {
        initComponents();
        this.manejo = new ManejoDeColecciones();
        this.manejo= manejo;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonVerConsultas = new javax.swing.JButton();
        botonAgregarConsultas = new javax.swing.JButton();
        botonVerTemas = new javax.swing.JButton();
        botonAgregarRespuesta = new javax.swing.JButton();
        botonEditarConsulta = new javax.swing.JButton();
        botonEliminarConsulta = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonVerConsultaPorTema = new javax.swing.JButton();
        botonConsultaTemaEID = new javax.swing.JButton();
        botonMostrarGrafico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenidos al sistema de Consulta Ciudadanas");

        jLabel2.setText("Que desea hacer?");

        botonVerConsultas.setText("Ver Consultas");
        botonVerConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerConsultasActionPerformed(evt);
            }
        });

        botonAgregarConsultas.setText("Agregar Consulta");
        botonAgregarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarConsultasActionPerformed(evt);
            }
        });

        botonVerTemas.setText("Ver Temas");
        botonVerTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerTemasActionPerformed(evt);
            }
        });

        botonAgregarRespuesta.setText("Agregar Respuesta");
        botonAgregarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarRespuestaActionPerformed(evt);
            }
        });

        botonEditarConsulta.setText("Editar Consultas");
        botonEditarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarConsultaActionPerformed(evt);
            }
        });

        botonEliminarConsulta.setText("Eliminar Consulta");
        botonEliminarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarConsultaActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonVerConsultaPorTema.setText("Ver Consulta por tema");
        botonVerConsultaPorTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerConsultaPorTemaActionPerformed(evt);
            }
        });

        botonConsultaTemaEID.setText("Ver Consulta por Tema e ID");
        botonConsultaTemaEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaTemaEIDActionPerformed(evt);
            }
        });

        botonMostrarGrafico.setText("Mostrar Grafico");
        botonMostrarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarGraficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonMostrarGrafico)
                            .addComponent(jLabel2))
                        .addGap(273, 273, 273))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonConsultaTemaEID)
                            .addComponent(botonVerConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAgregarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEditarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonVerConsultaPorTema, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(botonVerTemas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAgregarConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonEliminarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(botonSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerTemas)
                    .addComponent(botonVerConsultas))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerConsultaPorTema)
                    .addComponent(botonConsultaTemaEID))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarConsultas)
                    .addComponent(botonAgregarRespuesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEditarConsulta)
                    .addComponent(botonEliminarConsulta))
                .addGap(18, 18, 18)
                .addComponent(botonMostrarGrafico)
                .addGap(35, 35, 35)
                .addComponent(botonSalir)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerConsultasActionPerformed
       this.setVisible(false);
       this.mostrarConsultas = new VentanaConsultas(this, manejo);
       mostrarConsultas.setVisible(true);
       mostrarConsultas.mostrarCosultas();
    }//GEN-LAST:event_botonVerConsultasActionPerformed

    private void botonAgregarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarConsultasActionPerformed
        this.setVisible(false);
        this.anadirConsulta= new VentanaAnadir(manejo,this);
        this.anadirConsulta.setVisible(true);
    }//GEN-LAST:event_botonAgregarConsultasActionPerformed

    private void botonVerTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerTemasActionPerformed
        this.setVisible(false);
        this.mostrarTemas = new VentanaMostrarTemas (this,manejo);
        this.mostrarTemas.setVisible(true);
        mostrarTemas.mostrarTemas();
    }//GEN-LAST:event_botonVerTemasActionPerformed

    private void botonAgregarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarRespuestaActionPerformed
        this.setVisible(false);
        this.anadirRespuesta = new VentanaAgregarRespuesta(manejo,this);
        this.anadirRespuesta.setVisible(true);
        anadirRespuesta.mostrarTemas();
    }//GEN-LAST:event_botonAgregarRespuestaActionPerformed

    private void botonEditarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarConsultaActionPerformed
        editarConsulta = new VentanaEditarPregunta(manejo,this);
        editarConsulta.setVisible(true);
        editarConsulta.mostrarTemas();
    }//GEN-LAST:event_botonEditarConsultaActionPerformed

    private void botonEliminarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarConsultaActionPerformed
        eliminarConsulta = new VentanaEliminarConsulta(manejo,this);
        eliminarConsulta.setVisible(true);
        eliminarConsulta.mostrarTemas();
    }//GEN-LAST:event_botonEliminarConsultaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
        
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonVerConsultaPorTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerConsultaPorTemaActionPerformed
        this.setVisible(false);
        this.mostrarFiltro= new VentanaMostrarConFiltro(this,manejo);
        this.mostrarFiltro.setVisible(true);
    }//GEN-LAST:event_botonVerConsultaPorTemaActionPerformed

    private void botonConsultaTemaEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaTemaEIDActionPerformed
        this.setVisible(false);
        this.mostrarIdFiltro= new VentanaMostrarIdYTema(this, manejo);
        mostrarIdFiltro.setVisible(true);
    }//GEN-LAST:event_botonConsultaTemaEIDActionPerformed

    private void botonMostrarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarGraficoActionPerformed
        this.setVisible(false);
        this.mostrarGrafico = new VentanaMostrarGrafico (this, manejo);
        this.mostrarGrafico.setVisible(true);
        mostrarGrafico.mostrarTemas();
    }//GEN-LAST:event_botonMostrarGraficoActionPerformed

    /**
     * @param args the command line arguments
     */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarConsultas;
    private javax.swing.JButton botonAgregarRespuesta;
    private javax.swing.JButton botonConsultaTemaEID;
    private javax.swing.JButton botonEditarConsulta;
    private javax.swing.JButton botonEliminarConsulta;
    private javax.swing.JButton botonMostrarGrafico;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVerConsultaPorTema;
    private javax.swing.JButton botonVerConsultas;
    private javax.swing.JButton botonVerTemas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
