/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.*;
import java.util.*;
import javax.swing.*;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.*;
import java.io.*;
/**
 *
 * @author sebas
 */
public class VentanaMostrarConsultas extends javax.swing.JFrame {
    private ManejoDeColecciones manejo;
    private JFrame menuPrincipal;
    private JFrame editarConsulta;
    private VentanaErrorField aviso;
    /**
     * Creates new form VentanaConsultas
     */
    public VentanaMostrarConsultas(JFrame menuPrincipal , ManejoDeColecciones manejo) {
        initComponents();
        this.menuPrincipal= menuPrincipal;
        this.manejo= manejo;
        this.editarConsulta = editarConsulta;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();
        botonVolverAlMenu = new javax.swing.JButton();
        botonGenerarExel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tema", "ID", "Titulo Consulta", "Descripcion", "Muy a favor", "A favor", "Neutro", "En contra", "Muy en contra", "Likes", "Dislikes"
            }
        ));
        tablaConsulta.setRowHeight(30);
        jScrollPane1.setViewportView(tablaConsulta);
        if (tablaConsulta.getColumnModel().getColumnCount() > 0) {
            tablaConsulta.getColumnModel().getColumn(1).setMaxWidth(25);
        }

        botonVolverAlMenu.setText("Volver al menu");
        botonVolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAlMenuActionPerformed(evt);
            }
        });

        botonGenerarExel.setText("Generar Excel");
        botonGenerarExel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarExelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(botonVolverAlMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGenerarExel)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVolverAlMenu)
                    .addComponent(botonGenerarExel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAlMenuActionPerformed
        this.setVisible(false);
        this.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverAlMenuActionPerformed

    private void botonGenerarExelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarExelActionPerformed
        try{
            Workbook wb = new XSSFWorkbook();
            Sheet sheet = wb.createSheet("Data");
            Row rowCol = sheet.createRow(0);
            for (int i = 0; i < tablaConsulta.getColumnCount(); i++) {
                Cell cell = rowCol.createCell(i);
                cell.setCellValue(tablaConsulta.getColumnName(i));
            }
            for (int j = 0; j < tablaConsulta.getRowCount(); j++) {
                Row row = sheet.createRow(j+1);
                for (int k = 0; k < tablaConsulta.getColumnCount(); k++) {
                    Cell cell = row.createCell(k);
                    if (tablaConsulta.getValueAt(j, k) != null) {
                        cell.setCellValue(tablaConsulta.getValueAt(j, k).toString());
                    }
                }
            }
            FileOutputStream out = new FileOutputStream(new File("Datos.xlsx"));
            wb.write(out);
            wb.close();
            out.close();
            this.aviso = new VentanaErrorField("Excel realizado con exito!");
            this.aviso.setVisible(true);
            return;
        }catch(FileNotFoundException e){
                    System.out.println(e);
        }catch(IOException io){
                    System.out.println(io);
        }
    }//GEN-LAST:event_botonGenerarExelActionPerformed
 
    public void mostrarCosultas(){
        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            manejo.MatrizConsulta(),
            new String [] {
                "Tema", "ID", "Titulo Consulta", "Descripcion", "Muy a favor", "A favor", "Neutro", "En contra", "Muy en contra", "Likes", "Dislikes"
            }
        ));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerarExel;
    private javax.swing.JButton botonVolverAlMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaConsulta;
    // End of variables declaration//GEN-END:variables
}
