/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ManejoDeColecciones;
import Modelo.ArrayListConsultas;
import Modelo.ErrorTemaRepetidoException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;

/**
 * Clase VentanaEditarTema:
 * Interfaz grafica la cual se ocupa para editar un tema.
 */
public class VentanaEditarTema extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEditarTema
     */
    private ManejoDeColecciones manejo;
    private JFrame menuPrincipal;
    private VentanaErrorField error;
    
    public VentanaEditarTema(ManejoDeColecciones manejo , JFrame menu) {
        initComponents();
        this.manejo = manejo;
        this.menuPrincipal = menu;
        this.setLocationRelativeTo(null);
    }
   
    public void mostrarTemas(){
        HashMap<String,ArrayListConsultas> auxMapa= manejo.getConsultas();
        
        for(Map.Entry<String,ArrayListConsultas> set: auxMapa.entrySet()){
            if(this.manejo.getArrayCopia(set.getKey()).sizeConsultas() != 0)
                boxTemas.addItem(set.getKey()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boxTemas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        textoTema = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();
        botonEditarTema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese el tema que desea editar:");

        jLabel2.setText("Tema:");

        textoTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTemaActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver al menu");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonEditarTema.setText("Editar");
        botonEditarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarTemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoTema, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(boxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(botonEditarTema)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(boxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(textoTema, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVolver)
                    .addComponent(botonEditarTema))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTemaActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonEditarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarTemaActionPerformed
        String temaAEditar = (String)boxTemas.getSelectedItem();
        if(textoTema.getText().length() > 0)
        {
            try{
                this.manejo.EditarTema(temaAEditar , textoTema.getText());
                this.setVisible(false);
                this.dispose();
            }
            catch(ErrorTemaRepetidoException e){
                this.error = new VentanaErrorField("EL TEMA INGRESADO YA EXISTE");
                this.error.setVisible(true);
            }
            
        }
        else{
            this.error = new VentanaErrorField("Ingrese un tema valido");
            this.error.setVisible(true);
        }
    }//GEN-LAST:event_botonEditarTemaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditarTema;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox<String> boxTemas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textoTema;
    // End of variables declaration//GEN-END:variables
}
