/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ManejoDeColecciones;
import Modelo.ArrayListConsultas;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;

/**
 * VentanaAgregarRespuestaBinaria:
 * Interfaz grafica la cual se ocupa para agregar una Respuesta Binaria.
 */
public class VentanaAgregarRespuestaBinaria extends javax.swing.JFrame {
    private ManejoDeColecciones manejo;
    private JFrame menuPrincipal;
    /**
     * Creates new form VentanaAñadirRespuesta
     */
    public VentanaAgregarRespuestaBinaria(ManejoDeColecciones manejo, JFrame menuPrincipal) {
        initComponents();
        this.manejo=manejo;
        this.menuPrincipal= menuPrincipal;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonLikeDislike = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        boxID = new javax.swing.JComboBox();
        boxTemas = new javax.swing.JComboBox();
        botonMenuPrincipal = new javax.swing.JButton();
        botonOK = new javax.swing.JButton();
        botonDislike = new javax.swing.JRadioButton();
        botonLike = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Agregar Respuesta:");

        jLabel2.setText("Ingrese tema:");

        jLabel3.setText("Ingrese ID:");

        boxID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxIDActionPerformed(evt);
            }
        });

        boxTemas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxTemasItemStateChanged(evt);
            }
        });
        boxTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTemasActionPerformed(evt);
            }
        });

        botonMenuPrincipal.setText("Volver a menu");
        botonMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuPrincipalActionPerformed(evt);
            }
        });

        botonOK.setText("OK");
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });

        botonLikeDislike.add(botonDislike);
        botonDislike.setText("Dislike");
        botonDislike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDislikeActionPerformed(evt);
            }
        });

        botonLikeDislike.add(botonLike);
        botonLike.setText("Like");
        botonLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonLike)
                                .addGap(31, 31, 31)
                                .addComponent(botonDislike))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonMenuPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonOK)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(boxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonDislike)
                    .addComponent(botonLike))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMenuPrincipal)
                    .addComponent(botonOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxIDActionPerformed
        
    }//GEN-LAST:event_boxIDActionPerformed

    private void boxTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTemasActionPerformed
        
    }//GEN-LAST:event_boxTemasActionPerformed

    private void boxTemasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxTemasItemStateChanged
        String tema = (String)(boxTemas.getSelectedItem());
        mostrarIds(tema);
    }//GEN-LAST:event_boxTemasItemStateChanged

    private void botonMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuPrincipalActionPerformed
        this.setVisible(false);
        this.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonMenuPrincipalActionPerformed

    private void botonLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLikeActionPerformed

    private void botonDislikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDislikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDislikeActionPerformed

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed
        if(botonLike.isSelected()){
            manejo.agregarRespuesta((String)boxTemas.getSelectedItem(),(String)boxID.getSelectedItem(), true);
        }else{
            if(botonDislike.isSelected())
                manejo.agregarRespuesta((String)boxTemas.getSelectedItem(),(String)boxID.getSelectedItem(), false);
        } 
        this.setVisible(false);
        this.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonOKActionPerformed


    public void mostrarTemas(){
        HashMap<String,ArrayListConsultas> auxMapa = manejo.getConsultasBinarias();
        
        for(Map.Entry<String,ArrayListConsultas> set: auxMapa.entrySet()){
            if(this.manejo.getArrayCopia(set.getKey()).sizeConsultas() != 0)
                boxTemas.addItem(set.getKey());
        }
    }
    
    public void mostrarIds(String tema){
        ArrayListConsultas arrayListdeIDs = manejo.getConsultasBinariasPorTema(tema);
        boxID.removeAllItems();
        for (int i = 0; i < arrayListdeIDs.sizeConsultas(); i++) {
            boxID.addItem(Integer.toString(arrayListdeIDs.getConsulta(i).getIdConsulta()));
        }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonDislike;
    private javax.swing.JRadioButton botonLike;
    private javax.swing.ButtonGroup botonLikeDislike;
    private javax.swing.JButton botonMenuPrincipal;
    private javax.swing.JButton botonOK;
    private javax.swing.JComboBox boxID;
    private javax.swing.JComboBox boxTemas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
