/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ManejoDeColecciones;
import Modelo.ArrayListConsultas;
import Modelo.*;
import java.awt.*;
import java.util.*;
import javax.swing.JFrame;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 * VentanaMostrarGrafico: Interfaz grafica la cual se ocupa para mostrar el
 * grafico de las consultas.
 */
public class VentanaMostrarGrafico extends javax.swing.JFrame {

    private ManejoDeColecciones manejo;
    private JFrame menuPrincipal;

    /**
     * Creates new form VentanaMostrarGrafico
     */
    public VentanaMostrarGrafico(JFrame menuPrincipal, ManejoDeColecciones manejo) {
        initComponents();
        this.manejo = manejo;
        this.menuPrincipal = menuPrincipal;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textoIngresoA = new javax.swing.JLabel();
        textoIngresoB = new javax.swing.JLabel();
        graficarConsulta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelGrafico = new javax.swing.JPanel();
        nombreConsultaB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        descripcionConsulta = new javax.swing.JLabel();
        nombreTemaConsulta = new javax.swing.JLabel();
        nombreConsulta = new javax.swing.JLabel();
        nombreIdConsulta = new javax.swing.JLabel();
        volverMenuPrincipal = new javax.swing.JButton();
        boxTemas = new javax.swing.JComboBox();
        boxID = new javax.swing.JComboBox();
        botonConsultasSimple = new javax.swing.JRadioButton();
        botonConsultasMultiples = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        textoIngresoA.setText("Ingrese tema de la consulta");

        textoIngresoB.setText("Ingrese Id de la consulta");

        graficarConsulta.setText("Graficar");
        graficarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficarConsultaActionPerformed(evt);
            }
        });

        jLabel1.setText("Grafico Consulta ");

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        nombreConsultaB.setText("Nombre:");

        descripcionConsulta.setText("Descripcion:");

        volverMenuPrincipal.setText("Volver al menu");
        volverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuPrincipalActionPerformed(evt);
            }
        });

        boxTemas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxTemasItemStateChanged(evt);
            }
        });
        boxTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTemasActionPerformed(evt);
            }
        });

        boxID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxIDActionPerformed(evt);
            }
        });

        buttonGroup1.add(botonConsultasSimple);
        botonConsultasSimple.setText("Mostrar Consultas Simple");
        botonConsultasSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultasSimpleActionPerformed(evt);
            }
        });

        buttonGroup1.add(botonConsultasMultiples);
        botonConsultasMultiples.setText("Mostrar Consultas Multiples");
        botonConsultasMultiples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultasMultiplesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(nombreIdConsulta))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nombreConsultaB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreTemaConsulta))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(descripcionConsulta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreConsulta)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                                .addComponent(volverMenuPrincipal))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonConsultasMultiples)
                        .addGap(183, 183, 183)
                        .addComponent(botonConsultasSimple)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoIngresoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxTemas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(graficarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoIngresoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoIngresoA)
                            .addComponent(textoIngresoB))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69)
                        .addComponent(graficarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConsultasMultiples)
                    .addComponent(botonConsultasSimple))
                .addGap(93, 93, 93)
                .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreConsultaB)
                            .addComponent(nombreTemaConsulta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcionConsulta)
                            .addComponent(nombreConsulta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volverMenuPrincipal)
                        .addGap(12, 12, 12)))
                .addComponent(nombreIdConsulta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graficarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficarConsultaActionPerformed
        // TODO add your handling code here:
        panelGrafico.removeAll();
        if (botonConsultasSimple.isSelected()) {
            String tema = (String) boxTemas.getSelectedItem();
            String idConsulta = (String) boxID.getSelectedItem();
            ConsultaBinaria auxConsulta = (ConsultaBinaria) manejo.buscarConsultaPorId(tema, idConsulta);
            MostrarGraficoBinario(auxConsulta);
        } else {
            if (botonConsultasMultiples.isSelected()) {
                String tema = (String) boxTemas.getSelectedItem();
                String idConsulta = (String) boxID.getSelectedItem();
                ConsultaMultiple auxConsulta = (ConsultaMultiple) manejo.buscarConsultaPorId(tema, idConsulta);
                MostrarGraficoMultiple(auxConsulta);
            }
        }
    }//GEN-LAST:event_graficarConsultaActionPerformed

    public void MostrarGraficoMultiple(ConsultaMultiple auxConsulta) {
        RespuestaMultiple aux;
        nombreTemaConsulta.setText(auxConsulta.getTituloConsulta());
        nombreConsulta.setText(auxConsulta.getDescripcion());
        aux = (RespuestaMultiple) auxConsulta.getRespuestasConsulta();
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        datos.setValue(aux.getmFavor(), "Muy a Favor", "");
        datos.setValue(aux.getaFavor(), "Favor", "");
        datos.setValue(aux.getNeutro(), "Neutro", "");
        datos.setValue(aux.getContra(), "Contra", "");
        datos.setValue(aux.getmContra(), "Muy En Contra", "");
        JFreeChart graficoBarras = ChartFactory.createBarChart3D("Estadistica de votos", "", "Cantidad", datos, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel panel = new ChartPanel(graficoBarras);
        panel.setPreferredSize(new Dimension(400, 300));
        panelGrafico.setLayout(new BorderLayout());
        panelGrafico.add(panel, BorderLayout.NORTH);
        pack();
        repaint();
    }

    public void MostrarGraficoBinario(ConsultaBinaria auxConsulta) {
        RespuestaBinaria aux;
        String descripcion, titulo;
        nombreTemaConsulta.setText(auxConsulta.getTituloConsulta());
        nombreConsulta.setText(auxConsulta.getDescripcion());
        aux = (RespuestaBinaria) auxConsulta.getRespuestasConsulta();
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        datos.setValue(aux.getLikes(), "Likes", "");
        datos.setValue(aux.getDisLikes(), "Dislikes", "");
        JFreeChart graficoBarras = ChartFactory.createBarChart3D("Estadistica de votos", "", "Cantidad", datos, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel panel = new ChartPanel(graficoBarras);
        panel.setPreferredSize(new Dimension(400, 300));
        panelGrafico.setLayout(new BorderLayout());
        panelGrafico.add(panel, BorderLayout.NORTH);
        pack();
        repaint();
    }

    private void volverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuPrincipalActionPerformed
        // TODO add your handling code here:0
        this.setVisible(false);
        this.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMenuPrincipalActionPerformed

    private void boxTemasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxTemasItemStateChanged
        String tema = (String) (boxTemas.getSelectedItem());
        if (botonConsultasSimple.isSelected())
            mostrarIdsBinarias(tema);
        else {
            if (botonConsultasMultiples.isSelected()) {
                mostrarIdsMultiples(tema);
            }
        }
    }//GEN-LAST:event_boxTemasItemStateChanged

    private void boxTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTemasActionPerformed

    }//GEN-LAST:event_boxTemasActionPerformed

    private void boxIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxIDActionPerformed

    }//GEN-LAST:event_boxIDActionPerformed

    private void botonConsultasMultiplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultasMultiplesActionPerformed
        this.boxTemas.removeAllItems();
        this.mostrarTemasMultiples();
    }//GEN-LAST:event_botonConsultasMultiplesActionPerformed

    private void botonConsultasSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultasSimpleActionPerformed
        this.boxTemas.removeAllItems();
        this.mostrarTemasBinarios();
    }//GEN-LAST:event_botonConsultasSimpleActionPerformed

    public void mostrarTemasBinarios() {
        HashMap<String, ArrayListConsultas> auxMapa = manejo.getConsultasBinarias();
        for (Map.Entry<String, ArrayListConsultas> set : auxMapa.entrySet()) {
            if (this.manejo.getArrayCopia(set.getKey()).sizeConsultas() != 0) {
                boxTemas.addItem(set.getKey());
            }
        }
    }

    public void mostrarIdsBinarias(String tema) {
        ArrayListConsultas arrayListdeIDs = manejo.getConsultasBinariasPorTema(tema);
        boxID.removeAllItems();
        for (int i = 0; i < arrayListdeIDs.sizeConsultas(); i++) {
            boxID.addItem(Integer.toString(arrayListdeIDs.getConsulta(i).getIdConsulta()));
        }
    }

    public void mostrarTemasMultiples() {
        HashMap<String, ArrayListConsultas> auxMapa = manejo.getConsultasMultiples();
        for (Map.Entry<String, ArrayListConsultas> set : auxMapa.entrySet()) {
            if (this.manejo.getArrayCopia(set.getKey()).sizeConsultas() != 0) {
                boxTemas.addItem(set.getKey());
            }
        }
    }

    public void mostrarIdsMultiples(String tema) {
        ArrayListConsultas arrayListdeIDs = manejo.getConsultasMultiplesPorTema(tema);
        boxID.removeAllItems();
        for (int i = 0; i < arrayListdeIDs.sizeConsultas(); i++) {
            boxID.addItem(Integer.toString(arrayListdeIDs.getConsulta(i).getIdConsulta()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonConsultasMultiples;
    private javax.swing.JRadioButton botonConsultasSimple;
    private javax.swing.JComboBox boxID;
    private javax.swing.JComboBox boxTemas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel descripcionConsulta;
    private javax.swing.JButton graficarConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nombreConsulta;
    private javax.swing.JLabel nombreConsultaB;
    private javax.swing.JLabel nombreIdConsulta;
    private javax.swing.JLabel nombreTemaConsulta;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JLabel textoIngresoA;
    private javax.swing.JLabel textoIngresoB;
    private javax.swing.JButton volverMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
