/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ManejoDeColecciones;
import Modelo.ArrayListConsultas;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;

/**
 *
 * @author sebas
 */
public class VentanaMostrarConFiltro extends javax.swing.JFrame {
    private JFrame menuPrincipal;
    private ManejoDeColecciones manejo;
    private VentanaErrorField error;
    /**
     * Creates new form VentanaMostrarConFiltro
     */
    public VentanaMostrarConFiltro(JFrame menuPrincipal, ManejoDeColecciones manejo) {
        initComponents();
        this.menuPrincipal= menuPrincipal;
        this.manejo= manejo;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonVolverMenu = new javax.swing.JButton();
        botonMostrarConsultas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();
        boxTemas = new javax.swing.JComboBox();
        boxTemas2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese filtros:");

        jLabel2.setText("Tema 1");

        jLabel3.setText("Tema 2");

        botonVolverMenu.setText("Volver menu");
        botonVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverMenuActionPerformed(evt);
            }
        });

        botonMostrarConsultas.setText("Mostrar Consultas");
        botonMostrarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarConsultasActionPerformed(evt);
            }
        });

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tema", "Titulo Consulta", "Descripcion", "Likes", "Dislikes"
            }
        ));
        tablaConsulta.setRowHeight(30);
        jScrollPane1.setViewportView(tablaConsulta);

        boxTemas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxTemasItemStateChanged(evt);
            }
        });
        boxTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTemasActionPerformed(evt);
            }
        });

        boxTemas2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxTemas2ItemStateChanged(evt);
            }
        });
        boxTemas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTemas2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(130, 130, 130))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonMostrarConsultas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxTemas2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(botonVolverMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMostrarConsultas)
                    .addComponent(boxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxTemas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(botonVolverMenu)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverMenuActionPerformed
        this.setVisible(false);
        this.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverMenuActionPerformed

    private void botonMostrarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarConsultasActionPerformed
        if (((String)boxTemas.getSelectedItem()).equals((String)boxTemas2.getSelectedItem()) ) {
            this.error = new VentanaErrorField("Se ha seleccionado un tema repetido.");
            this.error.setVisible(true);
            return;
        }else{
           mostrarCosultas(); 
        }
        
    }//GEN-LAST:event_botonMostrarConsultasActionPerformed

    private void boxTemasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxTemasItemStateChanged
        
    }//GEN-LAST:event_boxTemasItemStateChanged

    private void boxTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTemasActionPerformed

    }//GEN-LAST:event_boxTemasActionPerformed

    private void boxTemas2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxTemas2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTemas2ItemStateChanged

    private void boxTemas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTemas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTemas2ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    public void mostrarCosultas(){
        String matriz[][] = new String [manejo.tamMapa()][6];
        HashMap<String,ArrayListConsultas> auxMapa= manejo.getConsultas();
        ArrayListConsultas arraylistFiltrado;
        arraylistFiltrado = manejo.motrarConsultasPorTema((String)boxTemas.getSelectedItem());
        int k=0;
        for (int  i= 0; i < 2; i++) {
            
            for (int j = 0; j < arraylistFiltrado.sizeConsultas(); j++) {
                matriz[k][0]=Integer.toString(arraylistFiltrado.getConsulta(j).getIdConsulta());
                matriz[k][1]=arraylistFiltrado.getConsulta(j).getTituloTema();
                matriz[k][2]=arraylistFiltrado.getConsulta(j).getTituloConsulta();
                matriz[k][3]=arraylistFiltrado.getConsulta(j).getDescripcion();
                matriz[k][4]=Integer.toString(arraylistFiltrado.getConsulta(j).getRespuestasConsulta().getLikes());
                matriz[k][5]=Integer.toString(arraylistFiltrado.getConsulta(j).getRespuestasConsulta().getDisLikes());
                k++;
            }
            
            arraylistFiltrado = manejo.motrarConsultasPorTema((String)boxTemas2.getSelectedItem());
        }
        
        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "ID", "Tema", "Titulo Consulta", "Descripcion", "Likes", "Dislikes"
            }
        ));
    }
    
    public void mostrarTemas(){
        HashMap<String,ArrayListConsultas> auxMapa= manejo.getConsultas();
        
        for(Map.Entry<String,ArrayListConsultas> set: auxMapa.entrySet()){
            boxTemas.addItem(set.getKey());
            boxTemas2.addItem(set.getKey());
        
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMostrarConsultas;
    private javax.swing.JButton botonVolverMenu;
    private javax.swing.JComboBox boxTemas;
    private javax.swing.JComboBox boxTemas2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaConsulta;
    // End of variables declaration//GEN-END:variables
}
