/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ManejoDeColecciones;
import Modelo.ArrayListConsultas;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;

/**
 *
 * @author sebas
 */
public class VentanaMostrarConFiltro extends javax.swing.JFrame {
    private JFrame menuPrincipal;
    private ManejoDeColecciones manejo;
    /**
     * Creates new form VentanaMostrarConFiltro
     */
    public VentanaMostrarConFiltro(JFrame menuPrincipal, ManejoDeColecciones manejo) {
        initComponents();
        this.menuPrincipal= menuPrincipal;
        this.manejo= manejo;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldTema1 = new javax.swing.JTextField();
        fieldTema2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonVolverMenu = new javax.swing.JButton();
        botonMostrarConsultas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese filtros:");

        fieldTema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTema1ActionPerformed(evt);
            }
        });

        fieldTema2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTema2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tema 1");

        jLabel3.setText("Tema 2");

        botonVolverMenu.setText("Volver menu");
        botonVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverMenuActionPerformed(evt);
            }
        });

        botonMostrarConsultas.setText("Mostrar Consultas");
        botonMostrarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarConsultasActionPerformed(evt);
            }
        });

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tema", "Titulo Consulta", "Descripcion", "Likes", "Dislikes"
            }
        ));
        tablaConsulta.setRowHeight(30);
        jScrollPane1.setViewportView(tablaConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(fieldTema1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fieldTema2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(botonMostrarConsultas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(botonVolverMenu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldTema1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTema2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(botonMostrarConsultas)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonVolverMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldTema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTema1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTema1ActionPerformed

    private void fieldTema2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTema2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTema2ActionPerformed

    private void botonVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverMenuActionPerformed
        this.setVisible(false);
        this.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverMenuActionPerformed

    private void botonMostrarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarConsultasActionPerformed
        mostrarCosultas();
    }//GEN-LAST:event_botonMostrarConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    public void mostrarCosultas(){
        String matriz[][] = new String [manejo.tamMapa()][6];
        HashMap<String,ArrayListConsultas> auxMapa= manejo.getConsultas();
        ArrayListConsultas arraylistFiltrado;
        arraylistFiltrado = manejo.motrarConsultasPorTema(fieldTema1.getText());
        for (int  i= 0; i < 2; i++) {
            for (int j = 0; j < arraylistFiltrado.sizeConsultas(); j++) {
                matriz[i][0]=Integer.toString(arraylistFiltrado.getConsulta(j).getIdConsulta());
                matriz[i][1]=arraylistFiltrado.getConsulta(j).getTituloTema();
                matriz[i][2]=arraylistFiltrado.getConsulta(j).getTituloConsulta();
                matriz[i][3]=arraylistFiltrado.getConsulta(j).getDescripcion();
                matriz[i][4]=Integer.toString(arraylistFiltrado.getConsulta(j).getRespuestasConsulta().getLikes());
                matriz[i][5]=Integer.toString(arraylistFiltrado.getConsulta(j).getRespuestasConsulta().getDisLikes());
                
            }
            
            arraylistFiltrado = manejo.motrarConsultasPorTema(fieldTema2.getText());
        }
        
        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "ID", "Tema", "Titulo Consulta", "Descripcion", "Likes", "Dislikes"
            }
        ));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMostrarConsultas;
    private javax.swing.JButton botonVolverMenu;
    private javax.swing.JTextField fieldTema1;
    private javax.swing.JTextField fieldTema2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaConsulta;
    // End of variables declaration//GEN-END:variables
}
