/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ManejoDeColecciones;
import java.io.IOException;
import javax.swing.JFrame;

/**
 * VentanaMostrarTemas: Interfaz grafica la cual se ocupa los temas.
 */
public class VentanaMostrarTemas extends javax.swing.JFrame {

    private ManejoDeColecciones manejo;
    private JFrame menuPrincipal;
    private ReportableStrategy reporte;
    private VentanaErrorField aviso;

    /**
     * Creates new form VentanaMostrarTemas
     */
    public VentanaMostrarTemas(JFrame menuPrincipal, ManejoDeColecciones manejo) {
        initComponents();
        this.manejo = manejo;
        this.menuPrincipal = menuPrincipal;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTemas = new javax.swing.JTable();
        botonVolverMenu = new javax.swing.JButton();
        botonGenerarTxt = new javax.swing.JButton();
        botonGeneralExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setText("Lista de todos los temas:");

        tablaTemas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Temas"
            }
        ));
        jScrollPane2.setViewportView(tablaTemas);

        botonVolverMenu.setText("Volver al menu");
        botonVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverMenuActionPerformed(evt);
            }
        });

        botonGenerarTxt.setText("Generar txt");
        botonGenerarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarTxtActionPerformed(evt);
            }
        });

        botonGeneralExcel.setText("Generar Excel");
        botonGeneralExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGeneralExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(botonVolverMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(botonGenerarTxt)
                        .addGap(65, 65, 65)
                        .addComponent(botonGeneralExcel)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGenerarTxt)
                    .addComponent(botonGeneralExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(botonVolverMenu)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverMenuActionPerformed
        this.setVisible(false);
        this.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverMenuActionPerformed

    private void botonGenerarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarTxtActionPerformed
        try{
            reporte = new ReporteTema(tablaTemas);
            reporte.generarTxt();
            this.aviso = new VentanaErrorField("Txt realizado con exito!");
            this.aviso.setVisible(true);
        }
        catch(IOException e){
            this.aviso = new VentanaErrorField("NO SE A PODIDO GENERAR EL ARCHIVO");
            this.aviso.setVisible(true);
        }
    }//GEN-LAST:event_botonGenerarTxtActionPerformed

    private void botonGeneralExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGeneralExcelActionPerformed
          try{
            reporte = new ReporteTema(tablaTemas);
            reporte.generarExcel();
            this.aviso = new VentanaErrorField("Excel realizado con exito!");
            this.aviso.setVisible(true);
        }
        catch(IOException e){
            this.aviso = new VentanaErrorField("NO SE A PODIDO GENERAR EL ARCHIVO");
            this.aviso.setVisible(true);
        }
        
        
    }//GEN-LAST:event_botonGeneralExcelActionPerformed

    public void mostrarTemas() {
        tablaTemas.setModel(new javax.swing.table.DefaultTableModel(
                manejo.matrizTemas(),
                new String[]{
                    "Temas"
                }
        ));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGeneralExcel;
    private javax.swing.JButton botonGenerarTxt;
    private javax.swing.JButton botonVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaTemas;
    // End of variables declaration//GEN-END:variables
}
